#!/usr/bin/env bash
# Refuse to commit worktree-local / generated artifacts. Both are .gitignored,
# so this guard only fires when someone force-adds them with `git add -f`:
#   - CONTRACT.md  — worktree-local spec contract, never committed (CLAUDE.md §1.1)
#   - *.xcodeproj  — generated by XcodeGen (`make gen`), never hand-edited or
#                    committed (CLAUDE.md §2 / §8)
# pre-commit only invokes this hook with paths matching its `files:` filter.
set -u

if [ "$#" -eq 0 ]; then
  exit 0
fi

echo "✗ Refusing to commit forbidden path(s):"
for f in "$@"; do
  echo "      $f"
done
echo ""
echo "  These are .gitignored — you only reach this via 'git add -f'. Unstage them:"
echo "      git restore --staged <path>"
echo "  (CONTRACT.md is worktree-local per §1.1; *.xcodeproj is XcodeGen output per §2/§8.)"
exit 1
